# Generated by Django 5.1.1 on 2024-11-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='studentid',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
