# Generated by Django 5.1.1 on 2024-11-17 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('c_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=70)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('dep_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Studnt',
        ),
        migrations.AddField(
            model_name='courses',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department'),
        ),
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.courses'),
        ),
    ]
