# Generated by Django 5.1.1 on 2024-11-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_c_name_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studnt',
            name='email',
            field=models.EmailField(default=0, max_length=254, unique=True),
        ),
    ]
