# Generated by Django 5.1.1 on 2024-11-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studnt_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studnt',
            name='phoneno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studnt',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
